-- Digital Hikers — Ops Ledger
-- Import in phpMyAdmin (cPanel) after creating your database.

SET NAMES utf8mb4;

CREATE TABLE IF NOT EXISTS users (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  username VARCHAR(60) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  role ENUM('admin','member') NOT NULL DEFAULT 'admin',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS clients (
  id INT AUTO_INCREMENT PRIMARY KEY,
  company VARCHAR(160) NOT NULL,
  contact VARCHAR(120) DEFAULT NULL,
  email VARCHAR(160) DEFAULT NULL,
  phone VARCHAR(40) DEFAULT NULL,
  address TEXT DEFAULT NULL,
  gstin VARCHAR(30) DEFAULT NULL,
  service VARCHAR(160) DEFAULT NULL,
  type VARCHAR(40) DEFAULT 'Retainer',
  since DATE DEFAULT NULL,
  status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
  notes TEXT DEFAULT NULL,
  archived TINYINT(1) NOT NULL DEFAULT 0,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS client_contacts (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  name VARCHAR(120) NOT NULL,
  role VARCHAR(80) DEFAULT NULL,
  email VARCHAR(160) DEFAULT NULL,
  phone VARCHAR(40) DEFAULT NULL,
  CONSTRAINT fk_cc_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS client_notes (
  id INT AUTO_INCREMENT PRIMARY KEY,
  client_id INT NOT NULL,
  body TEXT NOT NULL,
  author VARCHAR(120) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_cn_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoices (
  id INT AUTO_INCREMENT PRIMARY KEY,
  no VARCHAR(40) NOT NULL UNIQUE,
  client_id INT NOT NULL,
  invoice_date DATE NOT NULL,
  due_date DATE DEFAULT NULL,
  terms VARCHAR(30) DEFAULT 'Net 15',
  currency VARCHAR(5) NOT NULL DEFAULT 'INR',
  discount DECIMAL(12,2) NOT NULL DEFAULT 0,
  notes TEXT DEFAULT NULL,
  status VARCHAR(20) NOT NULL DEFAULT 'Draft',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_client FOREIGN KEY (client_id) REFERENCES clients(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS invoice_items (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  descr VARCHAR(255) DEFAULT NULL,
  qty DECIMAL(10,2) NOT NULL DEFAULT 1,
  rate DECIMAL(12,2) NOT NULL DEFAULT 0,
  sort_order INT NOT NULL DEFAULT 0,
  CONSTRAINT fk_item_inv FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payments (
  id INT AUTO_INCREMENT PRIMARY KEY,
  invoice_id INT NOT NULL,
  amt DECIMAL(12,2) NOT NULL,
  paid_on DATE NOT NULL,
  method VARCHAR(40) DEFAULT NULL,
  ref VARCHAR(80) DEFAULT NULL,
  note TEXT DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_pay_inv FOREIGN KEY (invoice_id) REFERENCES invoices(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS employees (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(120) NOT NULL,
  email VARCHAR(160) DEFAULT NULL,
  phone VARCHAR(40) DEFAULT NULL,
  role VARCHAR(120) DEFAULT NULL,
  dept VARCHAR(80) DEFAULT NULL,
  salary DECIMAL(12,2) NOT NULL DEFAULT 0,
  salary_type VARCHAR(30) DEFAULT 'Monthly',
  pay_date TINYINT DEFAULT 20,
  join_date DATE DEFAULT NULL,
  address TEXT DEFAULT NULL,
  bank VARCHAR(120) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  status ENUM('Active','Inactive') NOT NULL DEFAULT 'Active',
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS payroll (
  id INT AUTO_INCREMENT PRIMARY KEY,
  emp_id INT NOT NULL,
  month TINYINT NOT NULL,
  year SMALLINT NOT NULL,
  basic DECIMAL(12,2) NOT NULL DEFAULT 0,
  bonus DECIMAL(12,2) NOT NULL DEFAULT 0,
  deductions DECIMAL(12,2) NOT NULL DEFAULT 0,
  status ENUM('Pending','Paid') NOT NULL DEFAULT 'Pending',
  paid_on DATE DEFAULT NULL,
  method VARCHAR(40) DEFAULT NULL,
  ref VARCHAR(80) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY uniq_slip (emp_id, month, year),
  CONSTRAINT fk_pr_emp FOREIGN KEY (emp_id) REFERENCES employees(id) ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS activity_log (
  id INT AUTO_INCREMENT PRIMARY KEY,
  entity VARCHAR(30) NOT NULL,
  entity_id INT DEFAULT NULL,
  body VARCHAR(255) NOT NULL,
  tone VARCHAR(20) DEFAULT 'indigo',
  author VARCHAR(120) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_entity (entity, entity_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS settings (
  skey VARCHAR(60) PRIMARY KEY,
  sval TEXT
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

INSERT IGNORE INTO settings (skey, sval) VALUES
  ('company_name', 'Digital Hikers'),
  ('company_tagline', 'Digital marketing & AI automation'),
  ('company_address', 'Dhanbad · Bokaro, Jharkhand, India'),
  ('company_email', 'billing@digitalhikers.in'),
  ('company_phone', '+91 90000 00000'),
  ('company_bank', 'HDFC Bank · A/C 50100XXXXXXX · IFSC HDFC0000XXX'),
  ('invoice_prefix', 'INV');
CREATE TABLE IF NOT EXISTS documents (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  cat VARCHAR(40) NOT NULL DEFAULT 'Other',
  filename VARCHAR(80) NOT NULL,
  size INT NOT NULL DEFAULT 0,
  mime VARCHAR(80) DEFAULT NULL,
  uploaded_by VARCHAR(120) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_cat (cat)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
CREATE TABLE IF NOT EXISTS expenses (
  id INT AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(200) NOT NULL,
  cat VARCHAR(40) NOT NULL DEFAULT 'Other',
  amt DECIMAL(12,2) NOT NULL DEFAULT 0,
  spent_on DATE NOT NULL,
  method VARCHAR(40) DEFAULT NULL,
  notes TEXT DEFAULT NULL,
  receipt VARCHAR(80) DEFAULT NULL,
  created_by VARCHAR(120) DEFAULT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  INDEX idx_spent (spent_on),
  INDEX idx_cat (cat)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;
